version: '3.10'
services:
  gradio-app:
    build:
      context: .
      dockerfile: Dockerfile-gradio
    ports:
      - "7860:7860"
    depends_on:
      - movies_genre_api

  movies_genre_api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "5000:5000"

