# Use an official Python runtime as the parent image
FROM python:3.10-slim

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Expose port 7860 for the Gradio web app
EXPOSE 7860

# Run the Gradio Web App
CMD ["python", "movies_genre_webapp.py"]
