# Use an official Python runtime as the parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Install system dependencies required for Python packages
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    make \
    libstdc++6 \
    && apt-get clean

# Copy the current directory contents into the container
COPY . /app

RUN pip install gdown
RUN gdown --id 1FQJx_5gKx4SfjNkVflKtnEmoK_DWcxXX -O /app/DF_path.csv

# Install Python dependencies
RUN pip install --no-cache-dir --trusted-host pypi.python.org -r requirements-webapp.txt

# Expose port 7860 for the Gradio web app
EXPOSE 7860

# Define command to run the Gradio Web App
CMD ["python3", "movies_genre_webapp.py"]
